stages:
 - build

build_backend:
 stage: build
<<<<<<< HEAD
 image: maven:3.9-eclipse-temurin-17
=======
 image: maven:3.9-eclipse-temurin-21
>>>>>>> 4c0a1e744c5cb7524b91d51885d71bb0ef77ef7b
 script:
   - cd backend
   - mvn clean package

build_frontend:
 stage: build
 image: node:20
 script:
   - cd frontend
   - npm ci
   - npm run build