name: Build and Deploy

on:
  push:
    branches: [main]       # triggers on every push to main

jobs:

  build-and-push:
    runs-on: ubuntu-latest  # GitHub's cloud server builds this

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: anja18533s/employee-backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: anja18533s/employee-frontend:latest

  deploy:
    needs: build-and-push     # waits for build to finish
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}       # your remote server IP
          username: ${{ secrets.REMOTE_USER }}   # e.g. ubuntu
          password: ${{ secrets.REMOTE_PASSWORD }}     # private SSH key

          script: |
            docker pull anja18533s/employee-backend:latest
            docker pull anja18533s/employee-frontend:latest

            # create network if not exists
            docker network create app-network || true

            # stop old containers
            docker stop backend frontend postgres kafka || true
            docker rm backend frontend postgres kafka || true

            # start postgres
            docker run -d --name postgres \
            -e POSTGRES_DB=employee_db \
            -e POSTGRES_USER=employee_user \
            -e POSTGRES_PASSWORD=employee_password \
            --network app-network \
            postgres:16

            # start kafka (basic version)
            docker run -d --name kafka \
            --network app-network \
            -p 9092:9092 \
            apache/kafka:3.7.0

            # start backend
            docker run -d --name backend \
            -p 8080:8080 \
            -e DB_HOST=postgres \
            -e DB_PORT=5432 \
            -e DB_NAME=employee_db \
            -e DB_USER=employee_user \
            -e DB_PASSWORD=employee_password \
            -e KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
             --network app-network \
            anja18533s/employee-backend:latest

            # start frontend
            docker run -d --name frontend \
            -p 80:80 \
            --network app-network \
            anja18533s/employee-frontend:latest
